name: testing mini canvas
run-name: "trying to test mini canvas"
on:
  push:
    branches:
        -'main'
        -'twatkinz/actions'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
        - run: |
            pip install -r requirements.txt
            pip install pytest pytest-cov 
        - run: |
            pytest --cov=.



